# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-11-26 14:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='pub',
            field=models.CharField(max_length=200, null=True, verbose_name='pub'),
        ),
    ]
