# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-11-28 13:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0002_book_pub'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='market_price',
            field=models.DecimalField(decimal_places=2, default=9999, max_digits=12, verbose_name='零售价'),
        ),
        migrations.AddField(
            model_name='book',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='价格'),
        ),
        migrations.AlterField(
            model_name='book',
            name='pub',
            field=models.CharField(max_length=200, null=True, verbose_name='出版社'),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=100, verbose_name='书名'),
        ),
    ]
