# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-12-11 13:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0002_book_pub'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='market_price',
            field=models.IntegerField(default=1, verbose_name='图书零售价'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='price',
            field=models.IntegerField(default=1, verbose_name='图书价格'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='pub',
            field=models.CharField(default=1, max_length=200, verbose_name='出版社'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=100, unique=True, verbose_name='书名'),
        ),
    ]
