# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-12-11 13:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0003_auto_20201211_2120'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='')),
                ('age', models.IntegerField(default=1, verbose_name='')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='')),
            ],
        ),
    ]
