# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-12-19 13:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userinfo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.IntegerField(default=1, verbose_name='role'),
        ),
    ]
